CREATE TABLE ACCOUNT (
   ID NUMBER not null primary key,
    NAME    VARCHAR2(255),
    ACCOUNT_NUMBER  VARCHAR2(255) not null unique,
    ADDRESS  VARCHAR2(255),
    BALANCE  NUMBER(19,2),
    STATUS VARCHAR (255)
);

CREATE TABLE TRANSACTION (
    REQUEST_ID VARCHAR2(255) not null primary key,
    REQUESTER  VARCHAR2(255),
    TRANSACTION_TYPE VARCHAR2(255),
    TRANSACTION_TIME TIMESTAMP(6),
    SOURCE_ACCOUNT_NUMBER  VARCHAR2(255),
    DESTINATION_ACCOUNT_NUMBER  VARCHAR2(255),
    AMOUNT  NUMBER(19,2),
    NOTE VARCHAR (255)


);